service: microservices-example

provider:
  region: eu-west-1
  name: aws
  runtime: nodejs10.x
  memorySize: 128
  timeout: 7
  tracing: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"
  stage: ${opt:stage, 'staging'}

functions:
  createDataForDynamics:
    handler: src/server/cron.createDataForDynamics
    memorySize: 128
    timeout: 300
    events:
      - schedule: cron(0 5 * * ? *)

  createDataForDataPipe:
    handler: src/server/cron.createDataForDataPipe
    memorySize: 128
    timeout: 300
    events:
      - schedule: cron(0 0 * * ? *)

  